config/routes.rb
Milelias::Application.routes.draw do
  resources :categories

  get "home/index"

  resources :articles

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/article.rb
class Article < ActiveRecord::Base
  translates :title, :body
  attr_accessible :body, :category_id, :title

  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :slug

  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many :articles
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_presence :data

  def url_content
    url(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] if params[:locale].present?
  end

  def default_url_options(options = {})
    {locale: I18n.locale}
  end
end

app/controllers/articles_controller.rb
class ArticlesController < InheritedResources::Base
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = "Hello"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= raw article.body %></td>
    <td><%= article.category_id %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Body:</b>
  <%= raw @article.body %>
</p>

<p>
  <b>Category:</b>
  <%= @article.category_id %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Slug</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.slug %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Slug:</b>
  <%= @category.slug %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<% @title="Home1"%>
<div class= "row">
  <div class="large-6 columns"><div class="flex-video">
    <iframe width="420" height="270" src="//player.vimeo.com/video/74190830?title=0&amp;byline=0&amp;portrait=0" frameborder="0" allowfullscreen></iframe>
  </div></div>
  <div class="large-6 columns">
    <div class="panel callout radious">
      <h5><%= link_to t('moto1')%></h5>
    </div>
    <div class="panel callout radious">
      <h5><%=link_to  t('moto2')%></h5>
    </div>
    <div class="panel callout radious">
      <h5><%=link_to  t('moto3')%></h5>
    </div>
    <blockquote><%= t ('ceowords')%><cite><%= t ('ceo')%>, CEO</cite></blockquote>

  </div>

</div>
<div class= "white">

  <p><%= image_tag "brochure.jpg", :size => "180x180", :alt => "Edit Entry" %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <div class="row">
    <div class="small-12 columns">
      <div class="row">
        <div class="small-12 small-centered columns">
          <div class="small-4 push-8 columns">
            <div class= "homeupright">
              <%= image_tag "mail.png" %> info@milshield.gr <%= image_tag "phone.png" %> +302109835124

              <div class= "language">
                <%= link_to_unless I18n.locale == :en, "English", locale: "en" %> |
                <%= link_to_unless I18n.locale == :gr, "Ελληνικά", locale: "gr" %>
              </div>

            </div>
          </div>
          <div class="small-8 pull-4 columns">
            <div class="logo">
              <%=link_to image_tag("logomil.png", :alt => "Milshield logo",:width => 900, :height => 900), "/" %>
            </div>
          </div>

        </div>
      </div>
      <nav class="top-bar">
        <ul class="title-area">
          <li class="name"><!-- Leave this empty --></li>
          <section class="top-bar-section">
            <!-- Left Nav Section -->
            <ul class="left">
              <li class="divider"></li>
              <li><%= link_to t('menu1'), '/' %></li>
              <li class="divider"></li>
              <li><%= link_to t('menu2') %></li>
              <li class="divider"></li>
              <li><%= link_to t('menu3') %></li>
              <li class="divider"></li>
              <li><%= link_to t('menu4') %></li>
              <li class="divider"></li>
              <li><%= link_to t('menu5') %></li>
              <li class="divider"></li>
              <li><%= link_to t('menu6') %></li>
              <li class="divider"></li>
              <li class="has-dropdown"><a href="#"><%= link_to t('menu7') %></a>

                <ul class="dropdown">
                  <li class="has-dropdown"><a href="#">Dropdown Level 1a</a>

                    <ul class="dropdown">
                      <li><label>Dropdown Level 2 Label</label></li>
                      <li><a href="#">Dropdown Level 2a</a></li>
                      <li><a href="#">Dropdown Level 2b</a></li>
                      <li class="has-dropdown"><a href="#">Dropdown Level 2c</a>

                        <ul class="dropdown">
                          <li><label>Dropdown Level 3 Label</label></li>
                          <li><a href="#">Dropdown Level 3a</a></li>
                          <li><a href="#">Dropdown Level 3b</a></li>
                          <li class="divider"></li>
                          <li><a href="#">Dropdown Level 3c</a></li>
                        </ul>
                      </li>
                      <li><a href="#">Dropdown Level 2d</a></li>
                      <li><a href="#">Dropdown Level 2e</a></li>
                      <li><a href="#">Dropdown Level 2f</a></li>
                    </ul>
                  </li>
                  <li><a href="#">Dropdown Level 1b</a></li>
                  <li><a href="#">Dropdown Level 1c</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Dropdown Level 1d</a></li>
                  <li><a href="#">Dropdown Level 1e</a></li>
                  <li><a href="#">Dropdown Level 1f</a></li>
                  <li class="divider"></li>
                  <li><a href="#">See all &rarr;</a></li>
                </ul>
              </li>
            </ul>

            <!-- Right Nav Section
			    <ul class="right">

			          <li><%= image_tag "greek.png", :class => "language_icon" %></li>
					  <li><%= image_tag "usa.png", :class => "language_icon" %></li>


			    </ul>
			  </section>
			  </ul>  -->
      </nav>

        <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>